gregholliday/courses/urls.py
from django.conf.urls import url

from . import views

app_name = 'courses'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<course_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^add/$', views.add, name='add'),
    url(r'(?P<course_id>[0-9]+)/change/$', views.change, name='change'),
    url(r'^instructors/$', views.instructors, name='instructors'),
    url(r'^(?P<instructor_id>[0-9]+)/instdetail/$',views.instdetail,name='instdetail')
]

gregholliday/gregholliday/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gregholliday/courses/models.py
from django.db import models


class Instructors(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(null=True)
    phone = models.CharField(null=True, max_length=15)

    def __str__(self):
        return self.first_name + " " + self.last_name

    def name(self):
        return self.last_name + ", " + self.first_name


class Courses(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    duration = models.IntegerField()
    art = models.ImageField(null=True)
    instructor = models.ForeignKey(Instructors)

    def __str__(self):
        return self.title

gregholliday/courses/forms.py
from django import forms
from django.utils.safestring import mark_safe
from .models import Courses

DURATION_CHOICES = ((2, '2 Weeks'), (8, '8 weeks'))


# This code snippet was taken from
# https://wikis.utexas.edu/display/~bm6432/Django-Modifying+RadioSelect+Widget+to+have+horizontal+buttons
# it is used to render the radio buttons horizontally rather than vertically
class HorizRadioRenderer(forms.RadioSelect.renderer):
    def render(self):
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))


class CourseForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = ('title', 'description', 'duration', 'instructor', 'art',)
        widgets = {
            'duration': forms.RadioSelect(choices=DURATION_CHOICES, renderer=HorizRadioRenderer)
        }

gregholliday/courses/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse

from .models import Instructors, Courses
from .forms import CourseForm


def index(request):
    course_list = Courses.objects.all()
    context = {'course_list': course_list}
    return render(request, 'index.html', context)


def detail(request, course_id):
    course = get_object_or_404(Courses, pk=course_id)
    return render(request, 'detail.html', {'course': course})


def add(request):
    if request.method == "POST":
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect(reverse('courses:detail', kwargs={'course_id': post.id}))
    else:
        form = CourseForm()
    return render(request, 'addupdate.html', {'form': form})


def change(request, course_id):
    course = get_object_or_404(Courses, pk=course_id)
    if request.POST:
        form = CourseForm(request.POST, request.FILES, instance=course)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect(reverse('courses:detail', kwargs={'course_id': course_id}))
    else:
        form = CourseForm(instance=course)
    return render_to_response('addupdate.html', {'form': form}, context_instance=RequestContext(request))


def instructors(request):
    instructor_list = Instructors.objects.all().order_by('last_name')
    context = {'instructor_list': instructor_list}
    return render(request, 'instructors.html', context)


def instdetail(request, instructor_id):
    instructor = get_object_or_404(Instructors, pk=instructor_id)
    courses = Courses.objects.filter(instructor=instructor_id)
    return render(request,'instructor_detail.html', {'instructor': instructor, 'courses': courses})

gregholliday/courses/templates/addupdate.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}

{{ form.non_field_errors }}
<div class="container">
    <form class="form-horizontal" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-group">
            {{ form.title.errors }}
            <label for="{{form.title.id_for_label }}" class="col-sm-2">Course Title</label>
            <div class="col-sm-8">
             {{ form.title|add_class:"form-control"}}
            </div>
        </div>
        <div class="form-group">
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}" class="col-sm-2">Course Description</label>
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group">
            {{ form.description.errors }}
            <label  class="col-sm-2">Course Duration</label>
            <div class="col-sm-8">
                {{ form.duration }}
            </div>
        </div>
        <div class="form-group">
            {{ form.description.errors }}
            <label for="{{ form.instructor.id_for_label }}" class="col-sm-2">Instructor</label>
            <div class="col-sm-8">
                {{ form.instructor|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group">
            {{ form.description.errors }}
            <label for="{{ form.art.id_for_label }}" class="col-sm-2">Course Art</label>
            <div class="col-sm-8">
                {{ form.art|add_class:"class=btn btn-info" }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="save btn btn-info">Save</button>
            </div>
        </div>

    </form>
</div>


{% endblock %}

gregholliday/courses/templates/base.html
{% load staticfiles %}

<html>
<head>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" />
    <link href="{% static 'style.css' %}" rel="stylesheet" />
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#django-courses-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'courses:index' %}">Big Bang University</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="django-courses-navbar">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'courses:index' %}">Course Catalog <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'courses:add'  %}">Add Course</a></li>
        <li><a href="{% url 'courses:instructors'  %}">Instructor List</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block content %}
{% endblock %}
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

gregholliday/courses/templates/detail.html
{% extends "base.html" %}

{% block content %}
<div>
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <div class="row">
                <h1>{{ course.title }}</h1>
            </div>
            <div class="row">
                <h4>{{ course.description }}</h4>
            </div>
        </div>
        <div class="col-md-3">
            <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="{% url 'courses:change' course.id %}">Change</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <img src="{{MEDIA_URL}}{{ course.art.url }}" width="150" height="150"/>
        </div>
        <div class="col-md-3">
            <ul class="pull-right">
                <li>Instructor: {{ course.instructor }}</li>
                <li>Duration: {{ course.duration }} weeks</li>
            </ul>
        </div>
    </div>
</div>




{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{% endblock %}

gregholliday/courses/templates/index.html
{% extends "base.html" %}
{% block content %}
{% if course_list %}
<div>
    <div class="col-md-5 col-md-offset-3">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td width="50%">Course Title</td>
                    <td width="30%">Instructor</td>
                    <td width="20%">Duration</td>
                </tr>
            </thead>
            <tbody>
                {% for course in course_list %}
                <tr>
                    <td width="50%"><a href="{% url 'courses:detail' course.id %}">{{ course.title }}</a></td>
                    <td width="30%">{{ course.instructor }}</td>
                    <td width="20%">{{ course.duration }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
    <div class="alert alert-warning" role="alert">No courses were found.</div>
{% endif %}
{% endblock %}

gregholliday/courses/templates/instructor_detail.html
{% extends "base.html" %}

{% block content %}
<div>
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <div class="row">
                <p>First Name: {{ instructor.first_name }}</p>
            </div>
            <div class="row">
                <p>Last Name:  {{ instructor.last_name }}</p>
            </div>
            <div class="row">
                <p>Email:      {{ instructor.email }}</p>
            </div>
            <div class="row">
                <p>Phone:      {{ instructor.phone }}</p>
            </div>
        </div>
    </div>
    <div class="row">
        {% if courses %}
        <div>
            <div class="col-md-5 col-md-offset-3">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td width="50%">Course Title</td>
                            <td width="20%">Duration</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for course in courses %}
                        <tr>
                            <td width="50%"><a href="{% url 'courses:detail' course.id %}">{{ course.title }}</a></td>
                            <td width="20%">{{ course.duration }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% else %}
            <div class="alert alert-warning" role="alert">No courses assigned to this instructor.</div>
        {% endif %}
    </div>
</div>




{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{% endblock %}

gregholliday/courses/templates/instructors.html
{% extends "base.html" %}
{% block content %}
{% if instructor_list %}
<div>
    <div class="col-md-5 col-md-offset-3">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td width="33%">First Name</td>
                    <td width="33%">Last Name</td>
                    <td width="33%">Phone</td>
                </tr>
            </thead>
            <tbody>
                {% for instructor in instructor_list %}
                <tr>
                    <td width="33%"><a href="{% url 'courses:instdetail' instructor.id %}">{{ instructor.first_name }}</a></td>
                    <td width="33%"><a href="{% url 'courses:instdetail' instructor.id %}">{{ instructor.last_name }}</a></td>
                    <td width="33%">{{ instructor.phone }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
    <div class="alert alert-warning" role="alert">No instructors were found.</div>
{% endif %}
{% endblock %}